dist: trusty
addons:
  chrome: stable
language: ruby
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - BUNDLER_VER=`bundle --version`
  - if [[ ${BUNDLER_VER} =~ ^Bundler\ version\ 2.*$ ]]; then rvm @global do gem install bundler -v '< 2.0.0'; fi
  - if [[ ${BUNDLER_VER} =~ ^Bundler\ version\ 2.*$ ]]; then rvm @global do gem uninstall bundler -a -x -v '>= 2.0.0'; fi
  - bundle --version
rvm:
  - 2.5
  - 2.4
  - 2.3
  - 2.2
env:
  - REDMINE_VERSION=master VERBOSE=yes
  - REDMINE_VERSION=4.0-stable VERBOSE=yes
  - REDMINE_VERSION=3.4-stable VERBOSE=yes
matrix:
  exclude:
    - rvm: 2.5
      env: REDMINE_VERSION=3.4-stable VERBOSE=yes
    - rvm: 2.2
      env: REDMINE_VERSION=master VERBOSE=yes
install:
  - true
before_script:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin
  - google-chrome --version
  - chromedriver --version
script:
  - export PLUGIN=redmine_xlsx_format_issue_exporter
  - export WORKSPACE=$(pwd)/workspace
  - export PATH_TO_PLUGIN=$(pwd)
  - export PATH_TO_REDMINE=$WORKSPACE/redmine
  - mkdir $WORKSPACE
  - bash -x ./.travis-init.sh -r || exit 1
  - bash -x ./.travis-init.sh -i || exit 1
  - bash -x ./.travis-init.sh -t || exit 1
  - bash -x ./.travis-init.sh -u || exit 1
